import type { PresetConfig } from "./types";

/**
 * ARCTIC - Cold Polar Waters
 * Gray-blue seas under overcast skies with icy foam and moderate swells
 */
export const ARCTIC_PRESET: PresetConfig = {
  caustics: {
    enabled: true,
    surface: { strength: 0.1, scale: 0.02, speed: 0.25 },
  },
  clipmap: {
    baseSize: 800,
    levels: 5,
  },
  fog: {
    color: "#4c5357",
    enabled: true,
    fadeEnd: 5000,
    fadePower: 1,
    fadeStart: 0,
    skyBlendDistance: 10000,
  },
  color: {
    absorptionColor: "#44302c",
    transmissionColor: "#719cb8",
    waterColor: "#0f242f",
  },
  foam: {
    surface: {
      enabled: true,
      opacity: 0.1,
      color: "#ffffff",
      size: 134,
      coverage: 0.19,
      texture: "foam2",
    },
    waves: {
      enabled: false,
      opacity: 0.35,
      color: "#ffffff",
      size: 172,
      coverage: 0.25,
      peakIntensity: 0.35,
      windStretch: 0.48,
      crestCoverage: 0.35,
      waveWeight: 1,
      rippleWeight: 0.7,
      texture: "foam2",
      persistence: {
        decayTime: 0.5,
        windwardStrength: 0,
        crestStrength: 1,
      },
    },
    shoreline: {
      enabled: true,
      opacity: 0.1,
      size: 33,
      coverage: 0.84,
      range: 35,
      color: "#edf9fd",
      texture: "foam2",
    },
  },
  fresnel: {
    surface: {
      iorRatio: 1.3,
      normalStrength: 0.45,
      fadeStart: 0,
      fadePower: 0.5,
      refractionStrength: 0.15,
    },
    underwater: {
      waterAbsorption: 0.72,
      refractionIOR: 1.12,
      refractionStrength: 0.35,
      reflectionStrength: 0.45,
      normalStrength: 1.3,
    },
  },
  oceanFloor: {
    blendSoftness: 0.3,
    blendThreshold: 0.5,
    depth: 100,
    displacementScale: 140,
    displacementStrength: 8,
    enabled: true,
    lacunarity: 1.8,
    meshResolution: 64,
    normalScale: 0.2,
    persistence: 0.75,
    textureDisplacementStrength: 0.5,
    tileSize: 400,
    caustics: {
      depthAttenuation: 0,
      enabled: true,
      intensity: 0.9,
      scale: 150,
      waveDistortion: 0.26,
    },
    sunShafts: {
      enabled: true,
      intensity: 0.2,
    },
  },
  postProcessing: {
    enabled: true,
    bloom: {
      enabled: true,
      strength: 0.1,
      radius: 0.5,
      threshold: 1,
    },
    filmGrain: {
      enabled: true,
      intensity: 0.2,
    },
    vignette: {
      enabled: true,
      intensity: 0.3,
      smoothness: 0.8,
    },
    underwater: {
      distortionEnabled: true,
      distortionIntensity: 0.018,
      distortionScale: 4,
      distortionSpeed: 1.3,
      enabled: true,
      tintColor: "#ffffff",
    },
    rain: {
      color: "#b3bfcc",
      enabled: false,
      fadeDistance: 40,
      intensity: 0.33,
      rippleDecay: 1.0,
      rippleDensity: 0.25,
      rippleFadeEnd: 500,
      rippleSize: 2.5,
      rippleStrength: 0.5,
      streakLength: 1.0,
      streakWidth: 0.01,
      speed: 5.0,
      opacity: 0.5,
    },
    underwaterParticles: {
      color: "#ffffff",
      count: 1140,
      enabled: true,
      farDistance: 209,
      maxSize: 0.5,
      minSize: 0.1,
      nearDistance: 9,
      opacity: 0.5,
    },
  },
  spray: {
    bottomFadeStart: 0.0,
    bottomFadeStop: 0.15,
    duration: 1.5,
    enabled: true,
    fadeOutTime: 0.5,
    opacity: 0.4,
    respawnTime: 1.0,
    size: 27.5,
    spawnJitterTime: 0.0,
    stretchX: 1.88,
    stretchY: 1.0,
    submersionDepth: 0.5,
    velocityHeightFactor: 0.0,
    velocityScaleFactor: 0.0,
    velocityThreshold: 3.9,
  },
  ssr: {
    enabled: true,
    strength: 0.9,
  },
  sss: {
    enabled: true,
    intensity: 0.5,
    power: 2.8,
  },
  lighting: {
    ambient: {
      skyColor: "#adb3b8",
      groundColor: "#7b8b93",
      intensity: 0.98,
    },
  },
  sky: {
    source: {
      type: "hdri",
      url: "hdris/overcast_soil_puresky_4k.jpg",
    },
    brightness: 0.3,
    reflectionBlurDistance: 1500,
    reflectionDistanceBlur: 0.5,
    reflectionRoughness: 0.02,
    sun: {
      azimuth: 311,
      diskColor: "#fffef5",
      diskEnabled: false,
      diskEmissiveColor: "#fff8e0",
      diskEmissiveIntensity: 2,
      diskRadius: 0.015,
      elevation: 65,
      intensity: 0.7,
    },
  },
  sparkle: {
    enabled: true,
    fadeDistance: 1650,
    intensity: 1.0,
    minDistance: 0,
    power: 960,
  },
  wake: {
    foamBreakThreshold: 0,
    foamPersistence: 0.99,
    foamStrength: 0.8,
    friction: 0.25,
  },
  waves: {
    fft: {
      amplitude: 1,
      frequency: 0.67,
      animationSpeed: 3.1,
      windSpeed: 10.2,
      windDirection: 1,
      choppiness: 0.9,
      spectralSharpness: 0.3,
      standingWaveRatio: 0.51,
      cascades: {
        ripples: { scale: 360, amplitudeScale: 0.16 },
        waves: { scale: 2633, amplitudeScale: 0.44 },
      },
    },
    gerstner: {
      wavelength: 779,
      amplitude: 0.88,
      wavelengthSpread: 2.2,
      directionalSpread: 1.16,
    },
  },
};
