// Three.js Water Pro © 2025–2026 DRG Software Solutions LLC.
// Proprietary — licensed, not sold. See LICENSE.md.

import type { WaterSceneConfig } from "./types";

export const BLACK_FLAG_PRESET: WaterSceneConfig = {
  caustics: {
    enabled: true,
    surface: { strength: 0.6, scale: 0.025, speed: 0.22 },
  },
  clipmap: {
    baseSize: 200,
    levels: 5,
  },
  environment: {
    intensity: 0.5,
  },
  fog: {
    color: "#8b8f92",
    enabled: true,
    fadeEnd: 1210,
    fadePower: 0.5,
    fadeStart: 300,
    skyBlendDistance: 700,
  },
  color: {
    mode: "custom",
    absorptionColor: "#945b57",
    transmissionColor: "#226755",
    waterColor: "#224659",
  },
  foam: {
    surface: {
      enabled: true,
      opacity: 0.3,
      color: "#ffffff",
      size: 30,
      coverage: 0.21,
      texture: "foam4",
    },
    waves: {
      enabled: true,
      opacity: 0.6,
      color: "#ffffff",
      size: 9.1,
      windStretch: 0.47,
      texture: "foam3",
      persistence: {
        decayTime: 1.48,
        windwardStrength: 1.1,
        crestStrength: 0.99,
      },
    },
    shoreline: {
      enabled: true,
      opacity: 0.2,
      size: 18,
      coverage: 0.77,
      range: 3.95,
      color: "#edf9fd",
      texture: "foam3",
    },
  },
  fresnel: {
    surface: {
      iorRatio: 1.31,
      refractionStrength: 0.25,
    },
    underwater: {
      waterAbsorption: 0.55,
      refractionIOR: 1.1,
      refractionStrength: 0.4,
      reflectionStrength: 0.5,
      normalStrength: 1.2,
    },
  },
  oceanFloor: {
    blendSoftness: 0.3,
    blendThreshold: 0.5,
    depth: 8,
    displacementScale: 7,
    displacementStrength: 0.4,
    enabled: true,
    lacunarity: 1.8,
    meshResolution: 64,
    normalScale: 0.2,
    persistence: 0.75,
    textureDisplacementStrength: 0.5,
    tileSize: 20,
    caustics: {
      depthAttenuation: 0,
      enabled: true,
      intensity: 0.9,
      scale: 7.5,
      waveDistortion: 0.26,
    },
    sunShafts: {
      enabled: true,
      intensity: 0.2,
    },
  },
  postProcessing: {
    enabled: true,
    bloom: {
      enabled: true,
      strength: 0.3,
      radius: 0.5,
      threshold: 0.75,
    },
    filmGrain: {
      enabled: true,
      intensity: 0.06,
    },
    vignette: {
      enabled: true,
      intensity: 0.25,
      smoothness: 0.85,
    },
    underwater: {
      distortionEnabled: true,
      distortionIntensity: 0.015,
      distortionScale: 4,
      distortionSpeed: 1.2,
      enabled: true,
      tintColor: "#ffffff",
    },
    rain: {
      color: "#b3bfcc",
      enabled: false,
      fadeDistance: 40,
      intensity: 0.27,
      rippleDecay: 1,
      rippleDensity: 1,
      rippleFadeEnd: 60,
      rippleSize: 0.3,
      rippleStrength: 0.5,
      streakLength: 1,
      streakWidth: 0.01,
      speed: 5,
      opacity: 0.5,
    },
    underwaterParticles: {
      color: "#ffffff",
      count: 1000,
      enabled: true,
      farDistance: 40,
      maxSize: 0.15,
      minSize: 0.03,
      nearDistance: 2,
      opacity: 0.5,
    },
  },
  spray: {
    bottomFadeStart: 0,
    bottomFadeStop: 0.2,
    duration: 2.1,
    enabled: true,
    fadeOutTime: 0.47,
    opacity: 0.4,
    respawnTime: 1,
    size: 7,
    spawnJitterTime: 1,
    stretchX: 1.05,
    stretchY: 0.66,
    submersionDepth: 0.5,
    velocityHeightFactor: 0,
    velocityScaleFactor: 0.15,
    velocityThreshold: 1,
  },
  ssr: {
    enabled: true,
    strength: 1,
  },
  sss: {
    enabled: true,
    intensity: 0.35,
    power: 0.85,
  },
  sky: {
    source: {
      type: "hdri",
      url: "hdris/kloofendal_48d_partly_cloudy_puresky_4k.jpg",
    },
    brightness: 0.7,
    reflectionRoughness: 0.4,
    sun: {
      azimuth: 53,
      diskColor: "#fffef5",
      diskEnabled: true,
      diskEmissiveColor: "#fff8e0",
      diskEmissiveIntensity: 5,
      diskRadius: 0.015,
      elevation: 50,
      intensity: 1.5,
    },
  },
  sparkle: {
    enabled: true,
    fadeDistance: 110,
    intensity: 0.5,
    minDistance: 24,
    power: 1216,
  },
  wake: {
    foamBreakThreshold: 0,
    foamPersistence: 0.99,
    foamStrength: 0.8,
    friction: 0.25,
  },
  waves: {
    fft: {
      amplitude: 1,
      animationSpeed: 1,
      windSpeed: 15,
      windDirection: 1,
      choppiness: 1.5,
      peakWavelength: 47,
      spectralSharpness: 1.57,
      standingWaveRatio: 0.13,
      cascades: {
        maxScale: 1024,
      },
    },
  },
};
