import type { PresetConfig } from "./types";

/**
 * BLACK FLAG - High Seas Pirate
 * Strong winds, churning teal-tinted seas under a bright blue sky.
 * Dense crest foam with long-lived streaks and gerstner swell on top.
 */
export const BLACK_FLAG_PRESET: PresetConfig = {
  caustics: {
    enabled: true,
    surface: { strength: 0.6, scale: 0.025, speed: 0.22 },
  },
  clipmap: {
    baseSize: 800,
    levels: 5,
  },
  fog: {
    color: "#8f9ba3",
    enabled: true,
    fadeEnd: 10000,
    fadePower: 0.5,
    fadeStart: 1000,
    skyBlendDistance: 10000,
  },
  color: {
    absorptionColor: "#211817",
    transmissionColor: "#226755",
    waterColor: "#224659",
  },
  foam: {
    surface: {
      enabled: true,
      opacity: 0.3,
      color: "#ffffff",
      size: 261,
      coverage: 0.21,
      texture: "foam4",
    },
    waves: {
      enabled: true,
      opacity: 1,
      color: "#ffffff",
      size: 174,
      coverage: 0.16,
      crestCoverage: 0.25,
      peakIntensity: 0.4,
      windStretch: 0.47,
      waveWeight: 1,
      rippleWeight: 0.7,
      texture: "foam3",
      persistence: {
        decayTime: 3.03,
        windwardStrength: 1,
        crestStrength: 1,
      },
    },
    shoreline: {
      enabled: true,
      opacity: 0.2,
      size: 146,
      coverage: 0.8,
      range: 42,
      color: "#edf9fd",
      texture: "foam2",
    },
  },
  fresnel: {
    surface: {
      iorRatio: 1.31,
      normalStrength: 0.5,
      fadeStart: 100,
      fadePower: 4,
      refractionStrength: 0.2,
    },
    underwater: {
      waterAbsorption: 0.55,
      refractionIOR: 1.1,
      refractionStrength: 0.4,
      reflectionStrength: 0.5,
      normalStrength: 1.2,
    },
  },
  oceanFloor: {
    blendSoftness: 0.3,
    blendThreshold: 0.5,
    depth: 100,
    displacementScale: 140,
    displacementStrength: 8,
    enabled: true,
    lacunarity: 1.8,
    meshResolution: 64,
    normalScale: 0.2,
    persistence: 0.75,
    textureDisplacementStrength: 0.5,
    tileSize: 400,
    caustics: {
      depthAttenuation: 0,
      enabled: true,
      intensity: 0.9,
      scale: 150,
      waveDistortion: 0.26,
    },
    sunShafts: {
      enabled: true,
      intensity: 0.2,
    },
  },
  postProcessing: {
    enabled: true,
    bloom: {
      enabled: true,
      strength: 0.1,
      radius: 0.5,
      threshold: 1,
    },
    filmGrain: {
      enabled: true,
      intensity: 0.06,
    },
    vignette: {
      enabled: true,
      intensity: 0.25,
      smoothness: 0.85,
    },
    underwater: {
      distortionEnabled: true,
      distortionIntensity: 0.015,
      distortionScale: 4,
      distortionSpeed: 1.2,
      enabled: true,
      tintColor: "#ffffff",
    },
    rain: {
      color: "#b3bfcc",
      enabled: false,
      fadeDistance: 40,
      intensity: 0.27,
      rippleDecay: 1,
      rippleDensity: 1,
      rippleFadeEnd: 500,
      rippleSize: 2.5,
      rippleStrength: 0.5,
      streakLength: 1,
      streakWidth: 0.01,
      speed: 5,
      opacity: 0.5,
    },
    underwaterParticles: {
      color: "#ffffff",
      count: 1000,
      enabled: true,
      farDistance: 209,
      maxSize: 0.5,
      minSize: 0.1,
      nearDistance: 9,
      opacity: 0.5,
    },
  },
  spray: {
    bottomFadeStart: 0,
    bottomFadeStop: 0.2,
    duration: 2.1,
    enabled: true,
    fadeOutTime: 0.47,
    opacity: 0.4,
    respawnTime: 1,
    size: 71.9,
    spawnJitterTime: 1,
    stretchX: 1.05,
    stretchY: 0.66,
    submersionDepth: 2,
    velocityHeightFactor: 0,
    velocityScaleFactor: 0.15,
    velocityThreshold: 5.1,
  },
  ssr: {
    enabled: true,
    strength: 0.9,
  },
  sss: {
    enabled: true,
    intensity: 0.35,
    power: 0.85,
  },
  lighting: {
    ambient: {
      skyColor: "#d2e3f9",
      groundColor: "#abe0f2",
      intensity: 1.3,
    },
  },
  sky: {
    source: {
      type: "hdri",
      url: "hdris/kloofendal_43d_clear_puresky_4k.jpg",
    },
    brightness: 0.9,
    reflectionBlurDistance: 1500,
    reflectionDistanceBlur: 0.5,
    reflectionRoughness: 0.02,
    sun: {
      azimuth: 70,
      diskColor: "#fffef5",
      diskEnabled: false,
      diskEmissiveColor: "#fff8e0",
      diskEmissiveIntensity: 5,
      diskRadius: 0.015,
      elevation: 50,
      intensity: 2.5,
    },
  },
  sparkle: {
    enabled: true,
    fadeDistance: 1440,
    intensity: 0.5,
    minDistance: 0,
    power: 2048,
  },
  wake: {
    foamBreakThreshold: 0,
    foamPersistence: 0.99,
    foamStrength: 0.8,
    friction: 0.25,
  },
  waves: {
    fft: {
      amplitude: 1,
      frequency: 1,
      animationSpeed: 3.4,
      windSpeed: 25.9,
      windDirection: 0.9948376736367679,
      choppiness: 2.24,
      spectralSharpness: 0.65,
      standingWaveRatio: 0.32,
      cascades: {
        ripples: { scale: 326, amplitudeScale: 0.07 },
        waves: { scale: 1949, amplitudeScale: 0.33 },
      },
    },
    gerstner: {
      wavelength: 885,
      amplitude: 1.1,
      wavelengthSpread: 2.5,
      directionalSpread: 1.2,
    },
  },
};
