import type { PresetConfig } from "./types";

/**
 * DUSK - Twilight Calm
 * A low golden-pink sun resting near the horizon over gentle, glassy swells,
 * with warm haze blending into a dusk sky.
 */
export const DUSK_PRESET: PresetConfig = {
  caustics: {
    enabled: true,
    surface: { strength: 0.7, scale: 0.025, speed: 0.22 },
  },
  clipmap: {
    baseSize: 800,
    levels: 5,
  },
  fog: {
    color: "#f5ccd0",
    enabled: true,
    fadeEnd: 10000,
    fadePower: 0.7,
    fadeStart: 500,
    skyBlendDistance: 5450,
  },
  color: {
    absorptionColor: "#211a17",
    transmissionColor: "#1e675c",
    waterColor: "#39495b",
  },
  foam: {
    surface: {
      enabled: true,
      opacity: 0.25,
      color: "#ffffff",
      size: 233,
      coverage: 0.14,
      texture: "foam2",
    },
    waves: {
      enabled: true,
      opacity: 0.4,
      color: "#ffffff",
      size: 128,
      coverage: 0.33,
      crestCoverage: 0,
      peakIntensity: 0.35,
      windStretch: 0.42,
      waveWeight: 1.0,
      rippleWeight: 0.65,
      texture: "foam3",
      persistence: {
        decayTime: 0.5,
        windwardStrength: 0.23,
        crestStrength: 0.39,
      },
    },
    shoreline: {
      enabled: true,
      opacity: 0.1,
      size: 33,
      coverage: 0.84,
      range: 35,
      color: "#edf9fd",
      texture: "foam2",
    },
  },
  fresnel: {
    surface: {
      iorRatio: 1.33,
      normalStrength: 1.0,
      fadeStart: 250,
      fadePower: 2.5,
      refractionStrength: 0.1,
    },
    underwater: {
      waterAbsorption: 0.55,
      refractionIOR: 1.1,
      refractionStrength: 0.4,
      reflectionStrength: 0.45,
      normalStrength: 1.2,
    },
  },
  oceanFloor: {
    blendSoftness: 0.3,
    blendThreshold: 0.5,
    depth: 100,
    displacementScale: 140,
    displacementStrength: 8,
    enabled: true,
    lacunarity: 1.8,
    meshResolution: 64,
    normalScale: 0.2,
    persistence: 0.75,
    textureDisplacementStrength: 0.5,
    tileSize: 400,
    caustics: {
      depthAttenuation: 0,
      enabled: true,
      intensity: 0.9,
      scale: 150,
      waveDistortion: 0.26,
    },
    sunShafts: {
      enabled: true,
      intensity: 0.2,
    },
  },
  postProcessing: {
    enabled: true,
    bloom: {
      enabled: true,
      strength: 0.1,
      radius: 0.5,
      threshold: 1,
    },
    filmGrain: {
      enabled: true,
      intensity: 0.06,
    },
    vignette: {
      enabled: true,
      intensity: 0.25,
      smoothness: 0.85,
    },
    underwater: {
      distortionEnabled: true,
      distortionIntensity: 0.015,
      distortionScale: 4,
      distortionSpeed: 1.2,
      enabled: true,
      tintColor: "#ffffff",
    },
    rain: {
      color: "#b3bfcc",
      enabled: false,
      fadeDistance: 40,
      intensity: 0.5,
      rippleDecay: 1.0,
      rippleDensity: 1.0,
      rippleFadeEnd: 500,
      rippleSize: 2.5,
      rippleStrength: 0.5,
      streakLength: 1.0,
      streakWidth: 0.01,
      speed: 5.0,
      opacity: 0.5,
    },
    underwaterParticles: {
      color: "#ffffff",
      count: 1000,
      enabled: true,
      farDistance: 209,
      maxSize: 0.5,
      minSize: 0.1,
      nearDistance: 9,
      opacity: 0.5,
    },
  },
  spray: {
    bottomFadeStart: 0.0,
    bottomFadeStop: 0.1,
    duration: 1.75,
    enabled: true,
    fadeOutTime: 0.5,
    opacity: 0.4,
    respawnTime: 0.5,
    size: 30,
    spawnJitterTime: 0.5,
    stretchX: 1.5,
    stretchY: 1.0,
    submersionDepth: 0.0,
    velocityHeightFactor: 0.1,
    velocityScaleFactor: 0.0,
    velocityThreshold: 5.1,
  },
  ssr: {
    enabled: true,
    strength: 0.9,
  },
  sss: {
    enabled: true,
    intensity: 0.6,
    power: 2.3,
  },
  lighting: {
    ambient: {
      skyColor: "#f2e6d9",
      groundColor: "#3a4858",
      intensity: 0.34,
    },
  },
  sky: {
    source: {
      type: "hdri",
      url: "hdris/qwantani_dusk_2_puresky_4k.jpg",
    },
    brightness: 0.3,
    reflectionBlurDistance: 5000,
    reflectionDistanceBlur: 0.5,
    reflectionRoughness: 0.02,
    sun: {
      azimuth: 44,
      diskColor: "#f5ccd0",
      diskEnabled: false,
      diskEmissiveColor: "#fff8e0",
      diskEmissiveIntensity: 2,
      diskRadius: 0.015,
      elevation: 6,
      intensity: 2,
    },
  },
  sparkle: {
    enabled: true,
    fadeDistance: 1650,
    intensity: 1,
    minDistance: 0,
    power: 960,
  },
  wake: {
    foamBreakThreshold: 0,
    foamPersistence: 0.99,
    foamStrength: 0.8,
    friction: 0.25,
  },
  waves: {
    fft: {
      amplitude: 1,
      frequency: 1,
      animationSpeed: 2.8,
      windSpeed: 7,
      windDirection: 1.413716694115407,
      choppiness: 0.53,
      spectralSharpness: 1.05,
      standingWaveRatio: 0.51,
      cascades: {
        ripples: { scale: 200, amplitudeScale: 0.1 },
        waves: { scale: 3000, amplitudeScale: 0.5 },
      },
    },
    gerstner: {
      wavelength: 579,
      amplitude: 2.09,
      wavelengthSpread: 3,
      directionalSpread: 1.3,
    },
  },
};
