// Three.js Water Pro © 2025–2026 DRG Software Solutions LLC.
// Proprietary — licensed, not sold. See LICENSE.md.

import type { WaterSceneConfig } from "./types";

export const DUSK_PRESET: WaterSceneConfig = {
  caustics: {
    enabled: true,
    surface: { strength: 0.7, scale: 0.025, speed: 0.22 },
  },
  clipmap: {
    baseSize: 200,
    levels: 5,
  },
  environment: {
    intensity: 1.0,
  },
  fog: {
    color: "#4a4658",
    enabled: true,
    fadeEnd: 1960,
    fadePower: 0.7,
    fadeStart: 250,
    skyBlendDistance: 1350,
  },
  color: {
    mode: "custom",
    absorptionColor: "#876257",
    transmissionColor: "#1e675c",
    waterColor: "#112a37",
  },
  foam: {
    surface: {
      enabled: true,
      opacity: 0.25,
      color: "#ffffff",
      size: 30,
      coverage: 0.14,
      texture: "foam2",
    },
    waves: {
      enabled: false,
      opacity: 0.4,
      color: "#ffffff",
      size: 16,
      windStretch: 0.42,
      texture: "foam2",
      persistence: {
        decayTime: 0.5,
        windwardStrength: 1.1,
        crestStrength: 0.95,
      },
    },
    shoreline: {
      enabled: true,
      opacity: 0.1,
      size: 4,
      coverage: 0.84,
      range: 1.8,
      color: "#edf9fd",
      texture: "foam2",
    },
  },
  fresnel: {
    surface: {
      iorRatio: 1.33,
      refractionStrength: 0.1,
    },
    underwater: {
      waterAbsorption: 0.55,
      refractionIOR: 1.1,
      refractionStrength: 0.4,
      reflectionStrength: 0.45,
      normalStrength: 1.2,
    },
  },
  oceanFloor: {
    blendSoftness: 0.3,
    blendThreshold: 0.5,
    depth: 8,
    displacementScale: 7,
    displacementStrength: 0.4,
    enabled: true,
    lacunarity: 1.8,
    meshResolution: 64,
    normalScale: 0.2,
    persistence: 0.75,
    textureDisplacementStrength: 0.5,
    tileSize: 20,
    caustics: {
      depthAttenuation: 0,
      enabled: true,
      intensity: 0.9,
      scale: 7.5,
      waveDistortion: 0.26,
    },
    sunShafts: {
      enabled: true,
      intensity: 0.2,
    },
  },
  postProcessing: {
    enabled: true,
    bloom: {
      enabled: true,
      strength: 0.1,
      radius: 0.5,
      threshold: 1,
    },
    filmGrain: {
      enabled: true,
      intensity: 0.06,
    },
    vignette: {
      enabled: true,
      intensity: 0.25,
      smoothness: 0.85,
    },
    underwater: {
      distortionEnabled: true,
      distortionIntensity: 0.015,
      distortionScale: 4,
      distortionSpeed: 1.2,
      enabled: true,
      tintColor: "#ffffff",
    },
    rain: {
      color: "#b3bfcc",
      enabled: false,
      fadeDistance: 40,
      intensity: 0.5,
      rippleDecay: 1.0,
      rippleDensity: 1.0,
      rippleFadeEnd: 60,
      rippleSize: 0.3,
      rippleStrength: 0.5,
      streakLength: 1.0,
      streakWidth: 0.01,
      speed: 5.0,
      opacity: 0.5,
    },
    underwaterParticles: {
      color: "#ffffff",
      count: 1000,
      enabled: true,
      farDistance: 40,
      maxSize: 0.15,
      minSize: 0.03,
      nearDistance: 2,
      opacity: 0.5,
    },
  },
  spray: {
    bottomFadeStart: 0.0,
    bottomFadeStop: 0.1,
    duration: 1.75,
    enabled: true,
    fadeOutTime: 0.5,
    opacity: 0.4,
    respawnTime: 0.5,
    size: 3,
    spawnJitterTime: 0.5,
    stretchX: 1.5,
    stretchY: 1.0,
    submersionDepth: 0.0,
    velocityHeightFactor: 0.1,
    velocityScaleFactor: 0.0,
    velocityThreshold: 1,
  },
  ssr: {
    enabled: true,
    strength: 0.9,
  },
  sss: {
    enabled: true,
    intensity: 0.6,
    power: 2.3,
  },
  sky: {
    source: {
      type: "hdri",
      url: "hdris/qwantani_dusk_2_puresky_4k.jpg",
    },
    brightness: 0.2,
    reflectionRoughness: 0.15,
    sun: {
      azimuth: 44,
      diskColor: "#fdc4c9",
      diskEnabled: false,
      diskEmissiveColor: "#fff8e0",
      diskEmissiveIntensity: 2,
      diskRadius: 0.015,
      elevation: 6,
      intensity: 2,
    },
  },
  sparkle: {
    enabled: true,
    fadeDistance: 170,
    intensity: 1,
    minDistance: 0,
    power: 960,
  },
  wake: {
    foamBreakThreshold: 0,
    foamPersistence: 0.99,
    foamStrength: 0.8,
    friction: 0.25,
  },
  waves: {
    fft: {
      amplitude: 1,
      animationSpeed: 1,
      windSpeed: 7,
      windDirection: 1.413716694115407,
      choppiness: 0.73,
      peakWavelength: 140,
      spectralSharpness: 2.26,
      standingWaveRatio: 0.79,
      cascades: {
        maxScale: 1024,
      },
    },
  },
};
