// Three.js Water Pro © 2025–2026 DRG Software Solutions LLC.
// Proprietary — licensed, not sold. See LICENSE.md.

import type { WaterSceneConfig } from "./types";

export const FOGGY_PRESET: WaterSceneConfig = {
  caustics: {
    enabled: true,
    surface: { strength: 0.2, scale: 0.02, speed: 0.2 },
  },
  clipmap: {
    baseSize: 200,
    levels: 5,
  },
  environment: {
    intensity: 1.0,
  },
  fog: {
    color: "#6b6861",
    enabled: true,
    fadeEnd: 300,
    fadePower: 0.3,
    fadeStart: 25,
    skyBlendDistance: 660,
  },
  color: {
    mode: "custom",
    absorptionColor: "#ffecd4",
    transmissionColor: "#506570",
    waterColor: "#292929",
  },
  foam: {
    surface: {
      enabled: true,
      opacity: 0.45,
      color: "#e0e0e0",
      size: 24,
      coverage: 0.13,
      texture: "foam1",
    },
    waves: {
      enabled: true,
      opacity: 0.4,
      color: "#ffffff",
      size: 8,
      windStretch: 0.06,
      texture: "foam2",
      persistence: {
        decayTime: 0.93,
        windwardStrength: 0.81,
        crestStrength: 0.45,
      },
    },
    shoreline: {
      enabled: true,
      opacity: 0.1,
      size: 4,
      coverage: 0.84,
      range: 1.8,
      color: "#edf9fd",
      texture: "foam2",
    },
  },
  fresnel: {
    surface: {
      iorRatio: 1.59,
      refractionStrength: 0.1,
    },
    underwater: {
      waterAbsorption: 0.78,
      refractionIOR: 1.1,
      refractionStrength: 0.3,
      reflectionStrength: 0.4,
      normalStrength: 1.1,
    },
  },
  oceanFloor: {
    blendSoftness: 0.3,
    blendThreshold: 0.5,
    depth: 8,
    displacementScale: 7,
    displacementStrength: 0.4,
    enabled: true,
    lacunarity: 1.8,
    meshResolution: 64,
    normalScale: 0.2,
    persistence: 0.75,
    textureDisplacementStrength: 0.5,
    tileSize: 20,
    caustics: {
      depthAttenuation: 0,
      enabled: true,
      intensity: 0.9,
      scale: 7.5,
      waveDistortion: 0.26,
    },
    sunShafts: {
      enabled: true,
      intensity: 0.2,
    },
  },
  postProcessing: {
    enabled: true,
    bloom: {
      enabled: true,
      strength: 0.1,
      radius: 0.5,
      threshold: 1,
    },
    filmGrain: {
      enabled: true,
      intensity: 0.12,
    },
    vignette: {
      enabled: true,
      intensity: 0.5,
      smoothness: 0.7,
    },
    underwater: {
      distortionEnabled: true,
      distortionIntensity: 0.015,
      distortionScale: 4,
      distortionSpeed: 1,
      enabled: true,
      tintColor: "#ffffff",
    },
    rain: {
      color: "#ffffff",
      enabled: true,
      fadeDistance: 21,
      intensity: 0.8,
      rippleDecay: 1.6,
      rippleDensity: 0.75,
      rippleFadeEnd: 100,
      rippleSize: 0.3,
      rippleStrength: 1,
      streakLength: 1,
      streakWidth: 0.01,
      speed: 4.1,
      opacity: 0.06,
    },
    underwaterParticles: {
      color: "#ffffff",
      count: 1000,
      enabled: true,
      farDistance: 40,
      maxSize: 0.15,
      minSize: 0.03,
      nearDistance: 2,
      opacity: 0.5,
    },
  },
  spray: {
    bottomFadeStart: 0,
    bottomFadeStop: 0.15,
    duration: 1.5,
    enabled: true,
    fadeOutTime: 0.5,
    opacity: 0.4,
    respawnTime: 1,
    size: 3,
    spawnJitterTime: 0,
    stretchX: 1.88,
    stretchY: 1,
    submersionDepth: 0.15,
    velocityHeightFactor: 0,
    velocityScaleFactor: 0,
    velocityThreshold: 0.8,
  },
  ssr: {
    enabled: true,
    strength: 0.9,
  },
  sss: {
    enabled: true,
    intensity: 0.3,
    power: 3.5,
  },
  sky: {
    source: {
      type: "hdri",
      url: "hdris/overcast_soil_puresky_4k.jpg",
    },
    brightness: 0.2,
    reflectionRoughness: 0.15,
    sun: {
      azimuth: 265,
      diskColor: "#fffef5",
      diskEnabled: false,
      diskEmissiveColor: "#fff8e0",
      diskEmissiveIntensity: 3,
      diskRadius: 0.015,
      elevation: 90,
      intensity: 0.2,
    },
  },
  sparkle: {
    enabled: false,
    fadeDistance: 170,
    intensity: 1,
    minDistance: 0,
    power: 960,
  },
  wake: {
    foamBreakThreshold: 0,
    foamPersistence: 0.99,
    foamStrength: 0.8,
    friction: 0.25,
  },
  waves: {
    fft: {
      amplitude: 1,
      animationSpeed: 1,
      windSpeed: 5,
      windDirection: 0,
      choppiness: 1.67,
      peakWavelength: 110,
      spectralSharpness: 1,
      standingWaveRatio: 0.49,
      cascades: {
        maxScale: 1024,
      },
    },
  },
};
