import type { PresetConfig } from "./types";

/**
 * FOGGY - Thick Morning Mist
 * Muted waters in dense fog with reduced visibility and no sparkle
 */
export const FOGGY_PRESET: PresetConfig = {
  caustics: {
    enabled: true,
    surface: { strength: 0.2, scale: 0.02, speed: 0.2 },
  },
  clipmap: {
    baseSize: 800,
    levels: 5,
  },
  fog: {
    color: "#6b6861",
    enabled: true,
    fadeEnd: 2950,
    fadePower: 0.3,
    fadeStart: 250,
    skyBlendDistance: 6600,
  },
  color: {
    absorptionColor: "#2a221e",
    transmissionColor: "#506570",
    waterColor: "#292929",
  },
  foam: {
    surface: {
      enabled: true,
      opacity: 0.45,
      color: "#e0e0e0",
      size: 189,
      coverage: 0.13,
      texture: "foam1",
    },
    waves: {
      enabled: true,
      opacity: 0.65,
      color: "#ffffff",
      size: 149,
      coverage: 0.35,
      peakIntensity: 0.3,
      windStretch: 0.5,
      crestCoverage: 0.35,
      waveWeight: 1,
      rippleWeight: 0.7,
      texture: "foam3",
      persistence: {
        decayTime: 0.5,
        windwardStrength: 0.1,
        crestStrength: 0.25,
      },
    },
    shoreline: {
      enabled: true,
      opacity: 0.1,
      size: 33,
      coverage: 0.84,
      range: 35,
      color: "#edf9fd",
      texture: "foam2",
    },
  },
  fresnel: {
    surface: {
      iorRatio: 1.32,
      normalStrength: 0.79,
      fadeStart: 80,
      fadePower: 0.6,
      refractionStrength: 0.1,
    },
    underwater: {
      waterAbsorption: 0.78,
      refractionIOR: 1.1,
      refractionStrength: 0.3,
      reflectionStrength: 0.4,
      normalStrength: 1.1,
    },
  },
  oceanFloor: {
    blendSoftness: 0.3,
    blendThreshold: 0.5,
    depth: 100,
    displacementScale: 140,
    displacementStrength: 8,
    enabled: true,
    lacunarity: 1.8,
    meshResolution: 64,
    normalScale: 0.2,
    persistence: 0.75,
    textureDisplacementStrength: 0.5,
    tileSize: 400,
    caustics: {
      depthAttenuation: 0,
      enabled: true,
      intensity: 0.9,
      scale: 150,
      waveDistortion: 0.26,
    },
    sunShafts: {
      enabled: true,
      intensity: 0.2,
    },
  },
  postProcessing: {
    enabled: true,
    bloom: {
      enabled: true,
      strength: 0.1,
      radius: 0.5,
      threshold: 1,
    },
    filmGrain: {
      enabled: true,
      intensity: 0.12,
    },
    vignette: {
      enabled: true,
      intensity: 0.5,
      smoothness: 0.7,
    },
    underwater: {
      distortionEnabled: true,
      distortionIntensity: 0.015,
      distortionScale: 4,
      distortionSpeed: 1,
      enabled: true,
      tintColor: "#ffffff",
    },
    rain: {
      color: "#ffffff",
      enabled: true,
      fadeDistance: 21,
      intensity: 0.8,
      rippleDecay: 1.6,
      rippleDensity: 0.75,
      rippleFadeEnd: 1000,
      rippleSize: 8.5,
      rippleStrength: 1,
      streakLength: 1,
      streakWidth: 0.01,
      speed: 4.1,
      opacity: 0.06,
    },
    underwaterParticles: {
      color: "#ffffff",
      count: 1000,
      enabled: true,
      farDistance: 209,
      maxSize: 0.5,
      minSize: 0.1,
      nearDistance: 9,
      opacity: 0.5,
    },
  },
  spray: {
    bottomFadeStart: 0,
    bottomFadeStop: 0.15,
    duration: 1.5,
    enabled: true,
    fadeOutTime: 0.5,
    opacity: 0.4,
    respawnTime: 1,
    size: 27.5,
    spawnJitterTime: 0,
    stretchX: 1.88,
    stretchY: 1,
    submersionDepth: 0.5,
    velocityHeightFactor: 0,
    velocityScaleFactor: 0,
    velocityThreshold: 3.9,
  },
  ssr: {
    enabled: true,
    strength: 0.9,
  },
  sss: {
    enabled: true,
    intensity: 0.3,
    power: 3.5,
  },
  lighting: {
    ambient: {
      skyColor: "#cac2ba",
      groundColor: "#3c3f48",
      intensity: 1.64,
    },
  },
  sky: {
    source: {
      type: "hdri",
      url: "hdris/overcast_soil_puresky_4k.jpg",
    },
    brightness: 0.2,
    reflectionBlurDistance: 2000,
    reflectionDistanceBlur: 0.51,
    reflectionRoughness: 0.02,
    sun: {
      azimuth: 265,
      diskColor: "#fffef5",
      diskEnabled: false,
      diskEmissiveColor: "#fff8e0",
      diskEmissiveIntensity: 3,
      diskRadius: 0.015,
      elevation: 90,
      intensity: 0.2,
    },
  },
  sparkle: {
    enabled: false,
    fadeDistance: 1650,
    intensity: 1,
    minDistance: 0,
    power: 960,
  },
  wake: {
    foamBreakThreshold: 0,
    foamPersistence: 0.99,
    foamStrength: 0.8,
    friction: 0.25,
  },
  waves: {
    fft: {
      amplitude: 1,
      frequency: 1,
      animationSpeed: 2.9,
      windSpeed: 22.6,
      windDirection: 1.4486232791552935,
      choppiness: 1.5,
      spectralSharpness: 1,
      standingWaveRatio: 0.89,
      cascades: {
        ripples: { scale: 261, amplitudeScale: 0.05 },
        waves: { scale: 1430, amplitudeScale: 0.15 },
      },
    },
    gerstner: {
      wavelength: 785,
      amplitude: 2.88,
      wavelengthSpread: 2.48,
      directionalSpread: 0.9,
    },
  },
};
