import type { PresetConfig } from "./types";

/**
 * MOONLIT - Serene Night
 * Calm nighttime ocean with moonlight reflections and gentle swells
 */
export const MOONLIT_PRESET: PresetConfig = {
  caustics: {
    enabled: true,
    surface: { strength: 0.1, scale: 0.02, speed: 0.15 },
  },
  clipmap: {
    baseSize: 800,
    levels: 5,
  },
  fog: {
    color: "#212121",
    enabled: true,
    fadeEnd: 3800,
    fadePower: 0.7,
    fadeStart: 0,
    skyBlendDistance: 10000,
  },
  color: {
    absorptionColor: "#191414",
    transmissionColor: "#ffffff",
    waterColor: "#182325",
  },
  foam: {
    surface: {
      enabled: true,
      opacity: 0.05,
      color: "#c0c8d0",
      size: 206,
      coverage: 0.16,
      texture: "foam1",
    },
    waves: {
      enabled: true,
      opacity: 0.65,
      color: "#ffffff",
      size: 149,
      coverage: 0.4,
      peakIntensity: 0.2,
      windStretch: 0.5,
      crestCoverage: 0.2,
      waveWeight: 0.8,
      rippleWeight: 0.5,
      texture: "foam3",
      persistence: {
        decayTime: 0.5,
        windwardStrength: 0.1,
        crestStrength: 0.25,
      },
    },
    shoreline: {
      enabled: true,
      opacity: 0.05,
      size: 33,
      coverage: 0.84,
      range: 35,
      color: "#edf9fd",
      texture: "foam2",
    },
  },
  fresnel: {
    surface: {
      iorRatio: 1.33,
      normalStrength: 0.3,
      fadeStart: 150,
      fadePower: 4.1,
      refractionStrength: 0.5,
    },
    underwater: {
      waterAbsorption: 0.8,
      refractionIOR: 1.1,
      refractionStrength: 0.3,
      reflectionStrength: 0.55,
      normalStrength: 1.2,
    },
  },
  oceanFloor: {
    blendSoftness: 0.3,
    blendThreshold: 0.5,
    depth: 100,
    displacementScale: 140,
    displacementStrength: 8,
    enabled: true,
    lacunarity: 1.8,
    meshResolution: 64,
    normalScale: 0.2,
    persistence: 0.75,
    textureDisplacementStrength: 0.5,
    tileSize: 400,
    caustics: {
      depthAttenuation: 0,
      enabled: true,
      intensity: 0.9,
      scale: 150,
      waveDistortion: 0.26,
    },
    sunShafts: {
      enabled: true,
      intensity: 0.05,
    },
  },
  postProcessing: {
    enabled: true,
    bloom: {
      enabled: true,
      strength: 2.7,
      radius: 0.5,
      threshold: 0.75,
    },
    filmGrain: {
      enabled: true,
      intensity: 0.2,
    },
    vignette: {
      enabled: true,
      intensity: 0.45,
      smoothness: 0.8,
    },
    underwater: {
      distortionEnabled: true,
      distortionIntensity: 0.012,
      distortionScale: 4,
      distortionSpeed: 0.8,
      enabled: true,
      tintColor: "#ffffff",
    },
    rain: {
      color: "#b3bfcc",
      enabled: false,
      fadeDistance: 40,
      intensity: 0.1,
      rippleDecay: 1.0,
      rippleDensity: 1.0,
      rippleFadeEnd: 500,
      rippleSize: 2.5,
      rippleStrength: 0.5,
      streakLength: 1.0,
      streakWidth: 0.01,
      speed: 5.0,
      opacity: 0.5,
    },
    underwaterParticles: {
      color: "#ffffff",
      count: 1000,
      enabled: true,
      farDistance: 209,
      maxSize: 0.5,
      minSize: 0.1,
      nearDistance: 9,
      opacity: 0.1,
    },
  },
  spray: {
    bottomFadeStart: 0.0,
    bottomFadeStop: 0.15,
    duration: 1.5,
    enabled: true,
    fadeOutTime: 0.5,
    opacity: 0.4,
    respawnTime: 1.0,
    size: 27.5,
    spawnJitterTime: 0.0,
    stretchX: 1.88,
    stretchY: 1.0,
    submersionDepth: 0.5,
    velocityHeightFactor: 0.0,
    velocityScaleFactor: 0.0,
    velocityThreshold: 3.9,
  },
  ssr: {
    enabled: true,
    strength: 0.9,
  },
  sss: {
    enabled: true,
    intensity: 0.2,
    power: 3.0,
  },
  lighting: {
    ambient: {
      skyColor: "#5a6a85",
      groundColor: "#1b2238",
      intensity: 0.5,
    },
  },
  sky: {
    source: {
      type: "hdri",
      url: "hdris/NightSkyHDRI008_4K_HDR.jpg",
    },
    brightness: 0.4,
    reflectionBlurDistance: 10000,
    reflectionDistanceBlur: 0.51,
    reflectionRoughness: 0,
    sun: {
      azimuth: 65,
      diskColor: "#fffef5",
      diskEnabled: true,
      diskEmissiveColor: "#fff8e0",
      diskEmissiveIntensity: 2,
      diskRadius: 0.015,
      elevation: 36,
      intensity: 0.7,
    },
  },
  sparkle: {
    enabled: true,
    fadeDistance: 1650,
    intensity: 1.0,
    minDistance: 0,
    power: 960,
  },
  wake: {
    foamBreakThreshold: 0,
    foamPersistence: 0.99,
    foamStrength: 0.8,
    friction: 0.25,
  },
  waves: {
    fft: {
      amplitude: 1,
      frequency: 1.35,
      animationSpeed: 1.7,
      windSpeed: 10.9,
      windDirection: 0.9075712110370514,
      choppiness: 0.94,
      spectralSharpness: 0.3,
      standingWaveRatio: 0.86,
      cascades: {
        ripples: { scale: 139, amplitudeScale: 0.06 },
        waves: { scale: 1760, amplitudeScale: 0.24 },
      },
    },
    gerstner: {
      wavelength: 450,
      amplitude: 0,
      wavelengthSpread: 2.0,
      directionalSpread: 0.7,
    },
  },
};
