// Three.js Water Pro © 2025–2026 DRG Software Solutions LLC.
// Proprietary — licensed, not sold. See LICENSE.md.

import type { WaterSceneConfig } from "./types";

export const MOONLIT_PRESET: WaterSceneConfig = {
  caustics: {
    enabled: true,
    surface: { strength: 0.1, scale: 0.02, speed: 0.15 },
  },
  clipmap: {
    baseSize: 200,
    levels: 5,
  },
  environment: {
    intensity: 1.0,
  },
  fog: {
    color: "#000000",
    enabled: true,
    fadeEnd: 730,
    fadePower: 1.1,
    fadeStart: 280,
    skyBlendDistance: 875,
  },
  color: {
    mode: "custom",
    absorptionColor: "#5c4e4e",
    transmissionColor: "#ffffff",
    waterColor: "#182325",
  },
  foam: {
    surface: {
      enabled: true,
      opacity: 0.05,
      color: "#c0c8d0",
      size: 26,
      coverage: 0.16,
      texture: "foam1",
    },
    waves: {
      enabled: true,
      opacity: 0.65,
      color: "#ffffff",
      size: 19,
      windStretch: 0.5,
      texture: "foam3",
      persistence: {
        decayTime: 0.5,
        windwardStrength: 0.1,
        crestStrength: 0.25,
      },
    },
    shoreline: {
      enabled: true,
      opacity: 0.05,
      size: 4,
      coverage: 0.84,
      range: 1.8,
      color: "#edf9fd",
      texture: "foam2",
    },
  },
  fresnel: {
    surface: {
      iorRatio: 1.33,
      refractionStrength: 0.5,
    },
    underwater: {
      waterAbsorption: 0.8,
      refractionIOR: 1.1,
      refractionStrength: 0.3,
      reflectionStrength: 0.55,
      normalStrength: 1.2,
    },
  },
  oceanFloor: {
    blendSoftness: 0.3,
    blendThreshold: 0.5,
    depth: 8,
    displacementScale: 7,
    displacementStrength: 0.4,
    enabled: true,
    lacunarity: 1.8,
    meshResolution: 64,
    normalScale: 0.2,
    persistence: 0.75,
    textureDisplacementStrength: 0.5,
    tileSize: 20,
    caustics: {
      depthAttenuation: 0,
      enabled: true,
      intensity: 0.9,
      scale: 7.5,
      waveDistortion: 0.26,
    },
    sunShafts: {
      enabled: true,
      intensity: 0.05,
    },
  },
  postProcessing: {
    enabled: true,
    bloom: {
      enabled: true,
      strength: 2.7,
      radius: 0.5,
      threshold: 0.75,
    },
    filmGrain: {
      enabled: true,
      intensity: 0.2,
    },
    vignette: {
      enabled: true,
      intensity: 0.45,
      smoothness: 0.8,
    },
    underwater: {
      distortionEnabled: true,
      distortionIntensity: 0.012,
      distortionScale: 4,
      distortionSpeed: 0.8,
      enabled: true,
      tintColor: "#ffffff",
    },
    rain: {
      color: "#b3bfcc",
      enabled: false,
      fadeDistance: 40,
      intensity: 0.1,
      rippleDecay: 1.0,
      rippleDensity: 1.0,
      rippleFadeEnd: 60,
      rippleSize: 0.3,
      rippleStrength: 0.5,
      streakLength: 1.0,
      streakWidth: 0.01,
      speed: 5.0,
      opacity: 0.5,
    },
    underwaterParticles: {
      color: "#ffffff",
      count: 1000,
      enabled: true,
      farDistance: 40,
      maxSize: 0.15,
      minSize: 0.03,
      nearDistance: 2,
      opacity: 0.1,
    },
  },
  spray: {
    bottomFadeStart: 0.0,
    bottomFadeStop: 0.15,
    duration: 1.5,
    enabled: true,
    fadeOutTime: 0.5,
    opacity: 0.4,
    respawnTime: 1.0,
    size: 3,
    spawnJitterTime: 0.0,
    stretchX: 1.88,
    stretchY: 1.0,
    submersionDepth: 0.15,
    velocityHeightFactor: 0.0,
    velocityScaleFactor: 0.0,
    velocityThreshold: 0.8,
  },
  ssr: {
    enabled: true,
    strength: 0.9,
  },
  sss: {
    enabled: true,
    intensity: 0.2,
    power: 3.0,
  },
  sky: {
    source: {
      type: "hdri",
      url: "hdris/NightSkyHDRI008_4K_HDR.jpg",
    },
    brightness: 0.1,
    reflectionRoughness: 0.15,
    sun: {
      azimuth: 65,
      diskColor: "#fffef5",
      diskEnabled: true,
      diskEmissiveColor: "#fff8e0",
      diskEmissiveIntensity: 2,
      diskRadius: 0.015,
      elevation: 36,
      intensity: 1.5,
    },
  },
  sparkle: {
    enabled: true,
    fadeDistance: 170,
    intensity: 0.5,
    minDistance: 0,
    power: 960,
  },
  wake: {
    foamBreakThreshold: 0,
    foamPersistence: 0.99,
    foamStrength: 0.8,
    friction: 0.25,
  },
  waves: {
    fft: {
      amplitude: 1,
      animationSpeed: 1,
      windSpeed: 3,
      windDirection: 0.9075712110370514,
      choppiness: 0.94,
      peakWavelength: 80,
      spectralSharpness: 0.3,
      standingWaveRatio: 0.86,
      cascades: {
        maxScale: 1024,
      },
    },
  },
};
