import type { PresetConfig } from "./types";

/**
 * SEA OF THIEVES - Stylized Rolling Swells
 * Big dramatic waves with strong foam and rich colors, inspired by the game's aesthetic
 */
export const SEA_OF_THIEVES_PRESET: PresetConfig = {
  caustics: {
    enabled: true,
    surface: { strength: 0.6, scale: 0.025, speed: 0.22 },
  },
  clipmap: {
    baseSize: 800,
    levels: 5,
  },
  fog: {
    color: "#d2e5ea",
    enabled: true,
    fadeEnd: 6250,
    fadePower: 1.0,
    fadeStart: 600,
    skyBlendDistance: 4250,
  },
  color: {
    absorptionColor: "#331914",
    transmissionColor: "#41acb4",
    waterColor: "#074154",
  },
  foam: {
    surface: {
      enabled: true,
      opacity: 0.35,
      color: "#ffffff",
      size: 88,
      coverage: 0.24,
      texture: "foam2",
    },
    waves: {
      enabled: true,
      opacity: 0.85,
      color: "#ffffff",
      size: 290,
      coverage: 0.16,
      peakIntensity: 0.4,
      windStretch: 0.4,
      crestCoverage: 0.25,
      waveWeight: 1.0,
      rippleWeight: 0.7,
      texture: "foam2",
      persistence: {
        decayTime: 1.39,
        windwardStrength: 0.94,
        crestStrength: 1.01,
      },
    },
    shoreline: {
      enabled: true,
      opacity: 0.1,
      size: 33,
      coverage: 0.84,
      range: 35,
      color: "#edf9fd",
      texture: "foam2",
    },
  },
  fresnel: {
    surface: {
      fadePower: 2.5,
      fadeStart: 1000,
      iorRatio: 1.15,
      normalStrength: 0.41,
      refractionStrength: 0.25,
    },
    underwater: {
      waterAbsorption: 0.55,
      refractionIOR: 1.1,
      refractionStrength: 0.4,
      reflectionStrength: 0.5,
      normalStrength: 1.2,
    },
  },
  oceanFloor: {
    blendSoftness: 0.3,
    blendThreshold: 0.5,
    depth: 100,
    displacementScale: 140,
    displacementStrength: 8,
    enabled: true,
    lacunarity: 1.8,
    meshResolution: 64,
    normalScale: 0.2,
    persistence: 0.75,
    textureDisplacementStrength: 0.5,
    tileSize: 400,
    caustics: {
      depthAttenuation: 0,
      enabled: true,
      intensity: 0.9,
      scale: 150,
      waveDistortion: 0.26,
    },
    sunShafts: {
      enabled: true,
      intensity: 0.2,
    },
  },
  postProcessing: {
    enabled: true,
    bloom: {
      enabled: true,
      strength: 0.1,
      radius: 0.5,
      threshold: 1,
    },
    filmGrain: {
      enabled: true,
      intensity: 0.06,
    },
    vignette: {
      enabled: true,
      intensity: 0.25,
      smoothness: 0.85,
    },
    underwater: {
      distortionEnabled: true,
      distortionIntensity: 0.015,
      distortionScale: 4,
      distortionSpeed: 1.2,
      enabled: true,
      tintColor: "#ffffff",
    },
    rain: {
      color: "#b3bfcc",
      enabled: false,
      fadeDistance: 40,
      intensity: 0.27,
      rippleDecay: 1.0,
      rippleDensity: 1.0,
      rippleFadeEnd: 500,
      rippleSize: 2.5,
      rippleStrength: 0.5,
      streakLength: 1.0,
      streakWidth: 0.01,
      speed: 5.0,
      opacity: 0.5,
    },
    underwaterParticles: {
      color: "#ffffff",
      count: 1000,
      enabled: true,
      farDistance: 209,
      maxSize: 0.5,
      minSize: 0.1,
      nearDistance: 9,
      opacity: 0.5,
    },
  },
  spray: {
    bottomFadeStart: 0.0,
    bottomFadeStop: 0.15,
    duration: 1.5,
    enabled: true,
    fadeOutTime: 0.5,
    opacity: 0.4,
    respawnTime: 1.0,
    size: 27.5,
    spawnJitterTime: 0.0,
    stretchX: 1.88,
    stretchY: 1.0,
    submersionDepth: 0.5,
    velocityHeightFactor: 0.0,
    velocityScaleFactor: 0.0,
    velocityThreshold: 3.9,
  },
  ssr: {
    enabled: true,
    strength: 1.0,
  },
  sss: {
    enabled: true,
    intensity: 1.01,
    power: 1.2,
  },
  lighting: {
    ambient: {
      skyColor: "#c2e4ff",
      groundColor: "#9ce0f2",
      intensity: 1.77,
    },
  },
  sky: {
    source: {
      type: "hdri",
      url: "hdris/kloofendal_48d_partly_cloudy_puresky_4k.jpg",
    },
    brightness: 1.0,
    reflectionBlurDistance: 5600,
    reflectionDistanceBlur: 0.5,
    reflectionRoughness: 0.02,
    sun: {
      azimuth: 59,
      diskColor: "#fffef5",
      diskEnabled: true,
      diskEmissiveColor: "#fff8e0",
      diskEmissiveIntensity: 2,
      diskRadius: 0.015,
      elevation: 9,
      intensity: 0.5,
    },
  },
  sparkle: {
    enabled: true,
    fadeDistance: 1440,
    intensity: 2.1,
    minDistance: 0,
    power: 1296,
  },
  wake: {
    foamBreakThreshold: 0,
    foamPersistence: 0.99,
    foamStrength: 0.8,
    friction: 0.25,
  },
  waves: {
    fft: {
      amplitude: 1.0,
      frequency: 1.0,
      animationSpeed: 2.5,
      windSpeed: 25.7,
      windDirection: 4.258603374866164,
      choppiness: 1.5,
      spectralSharpness: 0.5,
      standingWaveRatio: 0.36,
      cascades: {
        ripples: { scale: 250, amplitudeScale: 0.12 },
        waves: { scale: 3000, amplitudeScale: 0.4 },
      },
    },
    gerstner: {
      wavelength: 1022,
      amplitude: 4.03,
      wavelengthSpread: 2.5,
      directionalSpread: 1.2,
    },
  },
};
