// Three.js Water Pro © 2025–2026 DRG Software Solutions LLC.
// Proprietary — licensed, not sold. See LICENSE.md.

import type { WaterSceneConfig } from "./types";

export const SEA_OF_THIEVES_PRESET: WaterSceneConfig = {
  caustics: {
    enabled: true,
    surface: { strength: 0.6, scale: 0.025, speed: 0.22 },
  },
  clipmap: {
    baseSize: 200,
    levels: 5,
  },
  environment: {
    intensity: 1.01,
  },
  fog: {
    color: "#8f9ba3",
    enabled: true,
    fadeEnd: 1000,
    fadePower: 0.5,
    fadeStart: 100,
    skyBlendDistance: 1000,
  },
  color: {
    mode: "custom",
    absorptionColor: "#a45b5b",
    transmissionColor: "#46fbf8",
    waterColor: "#006b8f",
  },
  foam: {
    surface: {
      enabled: true,
      opacity: 0.2,
      color: "#ffffff",
      size: 21,
      coverage: 0.15,
      texture: "foam1",
    },
    waves: {
      enabled: true,
      opacity: 1,
      color: "#ffffff",
      size: 6,
      windStretch: 0.41,
      texture: "foam3",
      persistence: {
        decayTime: 2.5,
        windwardStrength: 1.5,
        crestStrength: 1.5,
      },
    },
    shoreline: {
      enabled: true,
      opacity: 0.25,
      size: 25,
      coverage: 0.68,
      range: 5,
      color: "#edf9fd",
      texture: "foam3",
    },
  },
  fresnel: {
    surface: {
      iorRatio: 1.34,
      refractionStrength: 0.21,
    },
    underwater: {
      waterAbsorption: 0.55,
      refractionIOR: 1.1,
      refractionStrength: 0.4,
      reflectionStrength: 0.5,
      normalStrength: 1.2,
    },
  },
  oceanFloor: {
    blendSoftness: 0.3,
    blendThreshold: 0.5,
    depth: 8,
    displacementScale: 7,
    displacementStrength: 0.4,
    enabled: true,
    lacunarity: 1.8,
    meshResolution: 64,
    normalScale: 0.2,
    persistence: 0.75,
    textureDisplacementStrength: 0.5,
    tileSize: 20,
    caustics: {
      depthAttenuation: 0,
      enabled: true,
      intensity: 0.9,
      scale: 7.5,
      waveDistortion: 0.26,
    },
    sunShafts: {
      enabled: true,
      intensity: 0.2,
    },
  },
  postProcessing: {
    enabled: true,
    bloom: {
      enabled: true,
      strength: 0.1,
      radius: 0.5,
      threshold: 1,
    },
    filmGrain: {
      enabled: true,
      intensity: 0.06,
    },
    vignette: {
      enabled: true,
      intensity: 0.25,
      smoothness: 0.85,
    },
    underwater: {
      distortionEnabled: true,
      distortionIntensity: 0.015,
      distortionScale: 4,
      distortionSpeed: 1.2,
      enabled: true,
      tintColor: "#ffffff",
    },
    rain: {
      color: "#b3bfcc",
      enabled: false,
      fadeDistance: 40,
      intensity: 0.27,
      rippleDecay: 1.0,
      rippleDensity: 1.0,
      rippleFadeEnd: 60,
      rippleSize: 0.3,
      rippleStrength: 0.5,
      streakLength: 1.0,
      streakWidth: 0.01,
      speed: 5.0,
      opacity: 0.5,
    },
    underwaterParticles: {
      color: "#ffffff",
      count: 1000,
      enabled: true,
      farDistance: 40,
      maxSize: 0.15,
      minSize: 0.03,
      nearDistance: 2,
      opacity: 0.5,
    },
  },
  spray: {
    bottomFadeStart: 0.0,
    bottomFadeStop: 0.15,
    duration: 1.5,
    enabled: true,
    fadeOutTime: 0.5,
    opacity: 0.4,
    respawnTime: 1.0,
    size: 3,
    spawnJitterTime: 0.0,
    stretchX: 1.88,
    stretchY: 1.0,
    submersionDepth: 0.15,
    velocityHeightFactor: 0.0,
    velocityScaleFactor: 0.0,
    velocityThreshold: 0.8,
  },
  ssr: {
    enabled: true,
    strength: 0.9,
  },
  sss: {
    enabled: true,
    intensity: 1.06,
    power: 0.94,
  },
  sky: {
    source: {
      type: "hdri",
      url: "hdris/kloofendal_43d_clear_puresky_4k.jpg",
    },
    brightness: 0.7,
    reflectionRoughness: 0.12,
    sun: {
      azimuth: 41,
      diskColor: "#fffef5",
      diskEnabled: false,
      diskEmissiveColor: "#fff8e0",
      diskEmissiveIntensity: 5,
      diskRadius: 0.015,
      elevation: 27,
      intensity: 1,
    },
  },
  sparkle: {
    enabled: true,
    fadeDistance: 150,
    intensity: 0.5,
    minDistance: 0,
    power: 2048,
  },
  wake: {
    foamBreakThreshold: 0,
    foamPersistence: 0.99,
    foamStrength: 0.8,
    friction: 0.25,
  },
  waves: {
    fft: {
      amplitude: 1,
      animationSpeed: 1,
      windSpeed: 10.2,
      windDirection: 0.9948376736367679,
      choppiness: 1.96,
      peakWavelength: 130,
      spectralSharpness: 0.3,
      standingWaveRatio: 0.25,
      cascades: {
        maxScale: 1024,
      },
    },
  },
};
