import type { PresetConfig } from "./types";

/**
 * STORM - Rough Seas
 * Heavy winds, large breaking waves, dark skies and dense foam
 */
export const STORM_PRESET: PresetConfig = {
  caustics: {
    enabled: true,
    surface: {
      strength: 0.7,
      scale: 0.025,
      speed: 0.22,
    },
  },
  clipmap: {
    baseSize: 800,
    levels: 5,
  },
  fog: {
    color: "#5a5858",
    enabled: true,
    fadeEnd: 3100,
    fadePower: 0.3,
    fadeStart: 800,
    skyBlendDistance: 10000,
  },
  color: {
    absorptionColor: "#2a2827",
    transmissionColor: "#346565",
    waterColor: "#173240",
  },
  foam: {
    surface: {
      enabled: true,
      opacity: 0.25,
      color: "#ffffff",
      size: 242,
      coverage: 0.18,
      texture: "foam2",
    },
    waves: {
      enabled: true,
      opacity: 0.25,
      color: "#ffffff",
      size: 263,
      coverage: 0.33,
      crestCoverage: 0,
      peakIntensity: 0.35,
      windStretch: 0.41,
      waveWeight: 1,
      rippleWeight: 0.65,
      texture: "foam2",
      persistence: {
        decayTime: 2.95,
        windwardStrength: 1.03,
        crestStrength: 1.04,
      },
    },
    shoreline: {
      enabled: true,
      opacity: 0.15,
      size: 120,
      coverage: 0.88,
      range: 87,
      color: "#edf9fd",
      texture: "foam3",
    },
  },
  fresnel: {
    surface: {
      iorRatio: 1.32,
      normalStrength: 0.5,
      fadeStart: 0,
      fadePower: 1.9,
      refractionStrength: 0.1,
    },
    underwater: {
      waterAbsorption: 0.55,
      refractionIOR: 1.1,
      refractionStrength: 0.4,
      reflectionStrength: 0.45,
      normalStrength: 1.2,
    },
  },
  oceanFloor: {
    blendSoftness: 0.3,
    blendThreshold: 0.5,
    depth: 100,
    displacementScale: 140,
    displacementStrength: 8,
    enabled: true,
    lacunarity: 1.8,
    meshResolution: 64,
    normalScale: 0.2,
    persistence: 0.75,
    textureDisplacementStrength: 0.5,
    tileSize: 400,
    caustics: {
      depthAttenuation: 0,
      enabled: true,
      intensity: 0.9,
      scale: 150,
      waveDistortion: 0.26,
    },
    sunShafts: {
      enabled: true,
      intensity: 0.2,
    },
  },
  postProcessing: {
    enabled: true,
    bloom: {
      enabled: true,
      strength: 0.1,
      radius: 0.5,
      threshold: 1,
    },
    filmGrain: {
      enabled: true,
      intensity: 0.05,
    },
    vignette: {
      enabled: true,
      intensity: 0.45,
      smoothness: 0.85,
    },
    underwater: {
      distortionEnabled: true,
      distortionIntensity: 0.019,
      distortionScale: 3.5,
      distortionSpeed: 1.2,
      enabled: true,
      tintColor: "#ffffff",
    },
    rain: {
      color: "#b3bfcc",
      enabled: true,
      fadeDistance: 50,
      intensity: 0.71,
      rippleDecay: 0.8,
      rippleDensity: 2,
      rippleFadeEnd: 500,
      rippleSize: 6.5,
      rippleStrength: 0.55,
      streakLength: 1.35,
      streakWidth: 0.047,
      speed: 3.9,
      opacity: 0.11,
    },
    underwaterParticles: {
      color: "#ffffff",
      count: 2470,
      enabled: true,
      farDistance: 139,
      maxSize: 0.35,
      minSize: 0.23,
      nearDistance: 34,
      opacity: 0.5,
    },
  },
  spray: {
    bottomFadeStart: 0,
    bottomFadeStop: 0.1,
    duration: 1.5,
    enabled: true,
    fadeOutTime: 0.5,
    opacity: 0.4,
    respawnTime: 1,
    size: 42.3,
    spawnJitterTime: 0.5,
    stretchX: 1.88,
    stretchY: 1,
    submersionDepth: 0.25,
    velocityHeightFactor: 0,
    velocityScaleFactor: 0,
    velocityThreshold: 1.3,
  },
  ssr: {
    enabled: true,
    strength: 1,
  },
  sss: {
    enabled: true,
    intensity: 1.03,
    power: 2.15,
  },
  lighting: {
    ambient: {
      skyColor: "#a6adb9",
      groundColor: "#173240",
      intensity: 0.91,
    },
  },
  sky: {
    source: {
      type: "hdri",
      url: "hdris/overcast_soil_puresky_4k.jpg",
    },
    brightness: 0.2,
    reflectionBlurDistance: 1500,
    reflectionDistanceBlur: 0.5,
    reflectionRoughness: 0.02,
    sun: {
      azimuth: 216,
      diskColor: "#b7b0a9",
      diskEnabled: false,
      diskEmissiveColor: "#ffffff",
      diskEmissiveIntensity: 4,
      diskRadius: 0.015,
      elevation: 90,
      intensity: 1,
    },
  },
  sparkle: {
    enabled: false,
    fadeDistance: 1650,
    intensity: 1,
    minDistance: 0,
    power: 2048,
  },
  wake: {
    foamBreakThreshold: 0,
    foamPersistence: 0.99,
    foamStrength: 0.8,
    friction: 0.25,
  },
  waves: {
    fft: {
      amplitude: 1.62,
      frequency: 1.68,
      animationSpeed: 2,
      windSpeed: 25.6,
      windDirection: 0,
      choppiness: 1.66,
      spectralSharpness: 0.75,
      standingWaveRatio: 0,
      cascades: {
        ripples: { scale: 500, amplitudeScale: 0.07 },
        waves: { scale: 3338, amplitudeScale: 0.31 },
      },
    },
    gerstner: {
      wavelength: 895,
      amplitude: 3.78,
      wavelengthSpread: 2.25,
      directionalSpread: 1.09,
    },
  },
};
