// Three.js Water Pro © 2025–2026 DRG Software Solutions LLC.
// Proprietary — licensed, not sold. See LICENSE.md.

import type { WaterSceneConfig } from "./types";

export const STORM_PRESET: WaterSceneConfig = {
  caustics: {
    enabled: true,
    surface: { strength: 0.7, scale: 0.025, speed: 0.22 },
  },
  clipmap: {
    baseSize: 200,
    levels: 5,
  },
  environment: {
    intensity: 1.0,
  },
  fog: {
    color: "#5a5858",
    enabled: true,
    fadeEnd: 310,
    fadePower: 0.3,
    fadeStart: 80,
    skyBlendDistance: 1000,
  },
  color: {
    mode: "custom",
    absorptionColor: "#ffffff",
    transmissionColor: "#346565",
    waterColor: "#1b2a32",
  },
  foam: {
    surface: {
      enabled: true,
      opacity: 0.2,
      color: "#ffffff",
      size: 8.7,
      coverage: 0.16,
      texture: "foam1",
    },
    waves: {
      enabled: true,
      opacity: 0.35,
      color: "#ffffff",
      size: 6.8,
      windStretch: 0.38,
      texture: "foam3",
      persistence: {
        decayTime: 1.96,
        windwardStrength: 1.22,
        crestStrength: 1.01,
      },
    },
    shoreline: {
      enabled: true,
      opacity: 0.15,
      size: 60,
      coverage: 0.7,
      range: 3.4,
      color: "#edf9fd",
      texture: "foam3",
    },
  },
  fresnel: {
    surface: {
      iorRatio: 1.3,
      refractionStrength: 0.1,
    },
    underwater: {
      waterAbsorption: 0.55,
      refractionIOR: 1.1,
      refractionStrength: 0.4,
      reflectionStrength: 0.45,
      normalStrength: 1.2,
    },
  },
  oceanFloor: {
    blendSoftness: 0.3,
    blendThreshold: 0.5,
    depth: 8,
    displacementScale: 7,
    displacementStrength: 0.4,
    enabled: true,
    lacunarity: 1.8,
    meshResolution: 64,
    normalScale: 0.2,
    persistence: 0.75,
    textureDisplacementStrength: 0.5,
    tileSize: 20,
    caustics: {
      depthAttenuation: 0,
      enabled: true,
      intensity: 0.9,
      scale: 7.5,
      waveDistortion: 0.26,
    },
    sunShafts: {
      enabled: true,
      intensity: 0.2,
    },
  },
  postProcessing: {
    enabled: true,
    bloom: {
      enabled: true,
      strength: 0.1,
      radius: 0.5,
      threshold: 1,
    },
    filmGrain: {
      enabled: true,
      intensity: 0.05,
    },
    vignette: {
      enabled: true,
      intensity: 0.45,
      smoothness: 0.85,
    },
    underwater: {
      distortionEnabled: true,
      distortionIntensity: 0.019,
      distortionScale: 3.5,
      distortionSpeed: 1.2,
      enabled: true,
      tintColor: "#ffffff",
    },
    rain: {
      color: "#b3bfcc",
      enabled: true,
      fadeDistance: 50,
      intensity: 0.6,
      rippleDecay: 0.8,
      rippleDensity: 2.0,
      rippleFadeEnd: 60,
      rippleSize: 0.3,
      rippleStrength: 0.55,
      streakLength: 1.35,
      streakWidth: 0.026,
      speed: 5.0,
      opacity: 0.09,
    },
    underwaterParticles: {
      color: "#ffffff",
      count: 2470,
      enabled: true,
      farDistance: 28,
      maxSize: 0.1,
      minSize: 0.07,
      nearDistance: 7,
      opacity: 0.5,
    },
  },
  spray: {
    bottomFadeStart: 0.0,
    bottomFadeStop: 0.1,
    duration: 1.5,
    enabled: true,
    fadeOutTime: 0.5,
    opacity: 0.4,
    respawnTime: 1.0,
    size: 4,
    spawnJitterTime: 0.5,
    stretchX: 1.88,
    stretchY: 1.0,
    submersionDepth: 0.1,
    velocityHeightFactor: 0.0,
    velocityScaleFactor: 0.0,
    velocityThreshold: 0.3,
  },
  ssr: {
    enabled: true,
    strength: 1.0,
  },
  sss: {
    enabled: true,
    intensity: 1.03,
    power: 2.15,
  },
  sky: {
    source: {
      type: "hdri",
      url: "hdris/overcast_soil_puresky_4k.jpg",
    },
    brightness: 0.2,
    reflectionRoughness: 0.15,
    sun: {
      azimuth: 216,
      diskColor: "#b7b0a9",
      diskEnabled: false,
      diskEmissiveColor: "#ffffff",
      diskEmissiveIntensity: 4,
      diskRadius: 0.015,
      elevation: 90,
      intensity: 1,
    },
  },
  sparkle: {
    enabled: false,
    fadeDistance: 170,
    intensity: 1,
    minDistance: 0,
    power: 2048,
  },
  wake: {
    foamBreakThreshold: 0,
    foamPersistence: 0.99,
    foamStrength: 0.8,
    friction: 0.25,
  },
  waves: {
    fft: {
      amplitude: 1,
      animationSpeed: 1,
      windSpeed: 17,
      windDirection: 5.567600313861911,
      choppiness: 1.42,
      peakWavelength: 60,
      spectralSharpness: 2.55,
      standingWaveRatio: 0,
      cascades: {
        maxScale: 1024,
      },
    },
  },
};
