// Three.js Water Pro © 2025–2026 DRG Software Solutions LLC.
// Proprietary — licensed, not sold. See LICENSE.md.

import type { WaterSceneConfig } from "./types";

export const SUNSET_PRESET: WaterSceneConfig = {
  caustics: {
    enabled: true,
    surface: { strength: 0.6, scale: 0.025, speed: 0.22 },
  },
  clipmap: {
    baseSize: 200,
    levels: 5,
  },
  environment: {
    intensity: 1.0,
  },
  fog: {
    color: "#e0b48a",
    enabled: true,
    fadeEnd: 1000,
    fadePower: 0.4,
    fadeStart: 285,
    skyBlendDistance: 270,
  },
  color: {
    mode: "custom",
    absorptionColor: "#a88e8e",
    transmissionColor: "#50a890",
    waterColor: "#061b28",
  },
  foam: {
    surface: {
      enabled: true,
      opacity: 0.35,
      color: "#ffffff",
      size: 30,
      coverage: 0.17,
      texture: "foam2",
    },
    waves: {
      enabled: true,
      opacity: 0.15,
      color: "#ffffff",
      size: 30,
      windStretch: 0.47,
      texture: "foam3",
      persistence: {
        decayTime: 2.61,
        windwardStrength: 1,
        crestStrength: 1,
      },
    },
    shoreline: {
      enabled: true,
      opacity: 0.05,
      size: 13,
      coverage: 0.81,
      range: 2.2,
      color: "#edf9fd",
      texture: "foam2",
    },
  },
  fresnel: {
    surface: {
      iorRatio: 1.33,
      refractionStrength: 0.06,
    },
    underwater: {
      waterAbsorption: 0.55,
      refractionIOR: 1.1,
      refractionStrength: 0.4,
      reflectionStrength: 0.5,
      normalStrength: 1.2,
    },
  },
  oceanFloor: {
    blendSoftness: 0.3,
    blendThreshold: 0.5,
    depth: 8,
    displacementScale: 7,
    displacementStrength: 0.4,
    enabled: true,
    lacunarity: 1.8,
    meshResolution: 64,
    normalScale: 0.2,
    persistence: 0.75,
    textureDisplacementStrength: 0.5,
    tileSize: 20,
    caustics: {
      depthAttenuation: 0,
      enabled: true,
      intensity: 0.9,
      scale: 7.5,
      waveDistortion: 0.26,
    },
    sunShafts: {
      enabled: true,
      intensity: 0.2,
    },
  },
  postProcessing: {
    enabled: true,
    bloom: {
      enabled: true,
      strength: 0.3,
      radius: 0.5,
      threshold: 0.75,
    },
    filmGrain: {
      enabled: true,
      intensity: 0.06,
    },
    vignette: {
      enabled: true,
      intensity: 0.3,
      smoothness: 0.85,
    },
    underwater: {
      distortionEnabled: true,
      distortionIntensity: 0.015,
      distortionScale: 4,
      distortionSpeed: 1.2,
      enabled: true,
      tintColor: "#ffffff",
    },
    rain: {
      color: "#b3bfcc",
      enabled: false,
      fadeDistance: 40,
      intensity: 0.27,
      rippleDecay: 1.0,
      rippleDensity: 1.0,
      rippleFadeEnd: 60,
      rippleSize: 0.3,
      rippleStrength: 0.5,
      streakLength: 1.0,
      streakWidth: 0.01,
      speed: 5.0,
      opacity: 0.5,
    },
    underwaterParticles: {
      color: "#ffffff",
      count: 1000,
      enabled: true,
      farDistance: 40,
      maxSize: 0.15,
      minSize: 0.03,
      nearDistance: 2,
      opacity: 0.5,
    },
  },
  spray: {
    bottomFadeStart: 0.0,
    bottomFadeStop: 0.2,
    duration: 2.1,
    enabled: true,
    fadeOutTime: 0.47,
    opacity: 0.15,
    respawnTime: 1.0,
    size: 5,
    spawnJitterTime: 1.0,
    stretchX: 1.05,
    stretchY: 0.66,
    submersionDepth: 0.5,
    velocityHeightFactor: 0.0,
    velocityScaleFactor: 0.15,
    velocityThreshold: 1,
  },
  ssr: {
    enabled: true,
    strength: 0.71,
  },
  sss: {
    enabled: true,
    intensity: 0.3,
    power: 2,
  },
  sky: {
    source: {
      type: "hdri",
      url: "hdris/industrial_sunset_02_puresky_4k.jpg",
    },
    brightness: 0.3,
    reflectionRoughness: 0.15,
    sun: {
      azimuth: 54,
      diskColor: "#fdc1a0",
      diskEnabled: false,
      diskEmissiveColor: "#fff8e0",
      diskEmissiveIntensity: 5,
      diskRadius: 0.012,
      elevation: 2,
      intensity: 2.6,
    },
  },
  sparkle: {
    enabled: true,
    fadeDistance: 150,
    intensity: 0.5,
    minDistance: 0,
    power: 2048,
  },
  wake: {
    foamBreakThreshold: 0,
    foamPersistence: 0.99,
    foamStrength: 0.8,
    friction: 0.25,
  },
  waves: {
    fft: {
      amplitude: 1,
      animationSpeed: 1,
      windSpeed: 2.5,
      windDirection: 3.9618974020271276,
      choppiness: 1.51,
      peakWavelength: 20,
      spectralSharpness: 1.46,
      standingWaveRatio: 0.23,
      cascades: {
        maxScale: 1024,
      },
    },
  },
};
