name: Release Package

on:
  release:
    types: [created]

defaults:
  run:
    working-directory: packages/model-viewer

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.20.2
          registry-url: https://npm.pkg.github.com/
          scope: '@london-dynamics'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}